In [ ]:
import numpy as np

In [ ]:
a=np.array([[1, 2,3],[5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [ ]:
a1=np.random.randint(9,size=(5,5))
a1

array([[7, 7, 1, 3, 5],
       [0, 1, 6, 8, 0],
       [5, 6, 2, 6, 8],
       [3, 7, 5, 3, 6],
       [5, 5, 7, 3, 7]])

In [ ]:
a[1,1]=5
a

array([[1, 2, 3, 5],
       [5, 5, 7, 8]])

In [ ]:
a1[2:,1:4]

array([[6, 2, 6],
       [7, 5, 3],
       [5, 7, 3]])

In [ ]:
np.linspace(0, 10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
a1*5
for j in a1:
   if(a1[j]<=10):
       for i in a1:
           a2.append(i)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:

a2=[]
a1*5
for row_index in range(a1.shape[0]):  # Iterate through row indices
    if all(a1[row_index] <= 10):  # Check if all elements in the row are <= 10
        for i in a1:  # if True append each row of a1 to a2
            a2.append(i)

In [ ]:
import pandas as pd
df=pd.DataFrame(a1)
df

0  1  2  3  4
0  4  5  5  1  4
1  3  6  8  0  2
2  8  0  2  2  7
3  0  0  4  4  6
4  4  6  2  0  1

In [ ]:
df[0]=df.rename({"0":"9"})
df

In [ ]:
a.shape, a1. shape

In [ ]:
a. ndim

In [ ]:
a+a1

In [ ]:
a

In [ ]:
np.std(a)

2.034425935955617

In [ ]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.60943791, 1.94591015]])

In [ ]:
b=np.array([[6, 3,6,8], [9, 3,2,0]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [ ]:
b

array([[6, 3, 6, 8],
       [9, 3, 2, 0]])

In [ ]:
np. array_split(a, 1)

[array([[1, 2, 3],
        [5, 6, 7]])]

In [ ]:
np.add(a, b)

array([[ 7,  5,  9, 13],
       [14,  9,  9,  8]])

In [ ]:
np.dstack(a)

array([[[1, 5],
        [2, 6],
        [3, 7]]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a.itemsize#each val byte

8

In [ ]:
a.reshape(1,8)

array([[1, 2, 3, 5, 5, 6, 7, 8]])

In [ ]:
a.nbytes

64

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.random.randint(100,size=(5,3))

array([[20, 91, 13],
       [62, 41, 58],
       [47, 96, 37],
       [78, 71, 98],
       [78, 73, 19]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.genfromtxt("/content/Medicaldataset.csv",delimiter=",")

In [ ]:
a=np.loadtxt("/content/Medicaldataset.csv",delimiter=",")

ValueError: could not convert string 'Age' to float64 at row 0, column 1.

In [ ]:
a=np.nan_to_num(a)
a

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [6.300e+01, 1.000e+00, 6.600e+01, ..., 1.800e+00, 1.200e-02,
        0.000e+00],
       [2.000e+01, 1.000e+00, 9.400e+01, ..., 6.750e+00, 1.060e+00,
        0.000e+00],
       ...,
       [4.500e+01, 1.000e+00, 8.500e+01, ..., 1.240e+00, 4.250e+00,
        0.000e+00],
       [5.400e+01, 1.000e+00, 5.800e+01, ..., 5.800e+00, 3.590e-01,
        0.000e+00],
       [5.100e+01, 1.000e+00, 9.400e+01, ..., 5.089e+01, 1.770e+00,
        0.000e+00]])

In [ ]:
#dataset column
import numpy as np

# Save and load large datasets
arr = np.random.rand(1000000)  # 1M random values
np.save("dataset.npy", arr)     # Save as NumPy file (fast)
loaded_arr = np.load("dataset.npy")  # Load back
loaded_arr

array([0.49066623, 0.11481851, 0.14974933, ..., 0.42745303, 0.9843867 ,
       0.43096667])

In [ ]:
import pandas as pd
df=pd.DataFrame(a)
df#categorical should be nan, int into float

0    1     2      3      4      5      6      7    8
0      0.0  0.0   0.0    0.0    0.0    0.0   0.00  0.000  0.0
1     63.0  1.0  66.0  160.0   83.0  160.0   1.80  0.012  0.0
2     20.0  1.0  94.0   98.0   46.0  296.0   6.75  1.060  0.0
3     56.0  1.0  64.0  160.0   77.0  270.0   1.99  0.003  0.0
4     66.0  1.0  70.0  120.0   55.0  270.0  13.87  0.122  0.0
...    ...  ...   ...    ...    ...    ...    ...    ...  ...
1315  44.0  1.0  94.0  122.0   67.0  204.0   1.63  0.006  0.0
1316  66.0  1.0  84.0  125.0   55.0  149.0   1.33  0.172  0.0
1317  45.0  1.0  85.0  168.0  104.0   96.0   1.24  4.250  0.0
1318  54.0  1.0  58.0  117.0   68.0  443.0   5.80  0.359  0.0
1319  51.0  1.0  94.0  157.0   79.0  134.0  50.89  1.770  0.0

[1320 rows x 9 columns]

In [ ]:
df[2].max()

1111.0

In [ ]:
C=pd.read_csv("/content/Medicaldataset.csv")
C.head()

Age  Gender  Heart rate  Systolic blood pressure  Diastolic blood pressure  \
0   63       1          66                      160                        83   
1   20       1          94                       98                        46   
2   56       1          64                      160                        77   
3   66       1          70                      120                        55   
4   54       1          64                      112                        65   

   Blood sugar  CK-MB  Troponin    Result  
0        160.0   1.80     0.012  negative  
1        296.0   6.75     1.060  positive  
2        270.0   1.99     0.003  negative  
3        270.0  13.87     0.122  positive  
4        300.0   1.08     0.003  negative

In [ ]:
C["Heart rate"].max()

1111

In [ ]:
S=np.savetxt("myarray.txt",df,delimiter=" ")